services:
  db:
    image: postgres:16
    container_name: taskapi_db
    environment:
      POSTGRES_DB: taskapi
      POSTGRES_USER: taskapi
      POSTGRES_PASSWORD: taskapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: taskapi_api
    environment:
      DATABASE_URL: postgresql+psycopg2://taskapi:taskapi@db:5432/taskapi
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
